/**
 * Single source of truth for the portable binary's appended-payload layout.
 *
 * `dist/weavellm` is a self-extracting ELF:
 *
 *   [ELF stub (scripts/selfextract.c)]
 *   [payload: tar.gz of the Electrobun dev bundle]
 *   [trailer, TRAILER_LEN bytes, at EOF]
 *
 * The C stub reads the trailer at EOF and extracts to
 * $XDG_CACHE_HOME/weavellm/<payload sha256> before exec'ing the bundle
 * launcher. This module owns the byte layout; scripts/build-binary.ts writes
 * the trailer and ALSO renders `build/selfextract-trailer.h` from these same
 * constants (see renderTrailerHeader), so scripts/selfextract.c includes the
 * generated header and the two sides cannot drift.
 */

import { createHash } from "node:crypto";
import { join } from "node:path";

/** 8 ASCII bytes at offset 0 — validates the trailer before parsing. */
export const TRAILER_MAGIC = "WEAVELLM";

/** Layout version byte at offset 8 — bump on any trailer layout change. */
export const TRAILER_FORMAT_VERSION = 1;

export const TRAILER_MAGIC_LEN = Buffer.byteLength(TRAILER_MAGIC, "ascii");
export const TRAILER_VERSION_LEN = 1;
/** Payload byte length, uint64 little-endian. */
export const TRAILER_SIZE_LEN = 8;
/** sha256 of the payload, lowercase hex (also the extraction cache key). */
export const TRAILER_HASH_LEN = 64;

export const TRAILER_LEN =
  TRAILER_MAGIC_LEN + TRAILER_VERSION_LEN + TRAILER_SIZE_LEN + TRAILER_HASH_LEN;

export interface ParsedTrailer {
  payloadSize: number;
  sha256: string;
}

/** sha256 of the payload bytes, lowercase hex. */
export function payloadSha256Hex(payload: Buffer): string {
  return createHash("sha256").update(payload).digest("hex");
}

/** Build the 81-byte trailer appended after the payload at EOF. */
export function buildTrailer(payload: Buffer): Buffer {
  const size = Buffer.allocUnsafe(TRAILER_SIZE_LEN);
  size.writeBigUInt64LE(BigInt(payload.length));
  return Buffer.concat([
    Buffer.from(TRAILER_MAGIC, "ascii"),
    Buffer.from([TRAILER_FORMAT_VERSION]),
    size,
    Buffer.from(payloadSha256Hex(payload), "ascii"),
  ]);
}

/** Parse and validate a trailer buffer; null when magic/version are wrong. */
export function parseTrailer(buf: Buffer): ParsedTrailer | null {
  if (buf.length < TRAILER_LEN) return null;
  if (buf.subarray(0, TRAILER_MAGIC_LEN).toString("ascii") !== TRAILER_MAGIC) {
    return null;
  }
  if (buf[TRAILER_MAGIC_LEN] !== TRAILER_FORMAT_VERSION) return null;
  const payloadSize = Number(
    buf.readBigUInt64LE(TRAILER_MAGIC_LEN + TRAILER_VERSION_LEN),
  );
  const sha256 = buf
    .subarray(TRAILER_MAGIC_LEN + TRAILER_VERSION_LEN + TRAILER_SIZE_LEN)
    .toString("ascii");
  return { payloadSize, sha256 };
}

/**
 * Render the C header included by scripts/selfextract.c. Generated at build
 * time into build/selfextract-trailer.h so the byte layout has exactly one
 * source of truth (this module).
 */
export function renderTrailerHeader(): string {
  return [
    "/* Generated by scripts/selfextract-layout.ts — single source of truth for",
    " * the appended-payload trailer layout. Do not edit by hand. */",
    "#ifndef WEAVELLM_SELFEXTRACT_TRAILER_H",
    "#define WEAVELLM_SELFEXTRACT_TRAILER_H",
    "",
    `#define WEAVELLM_TRAILER_MAGIC "${TRAILER_MAGIC}"`,
    `#define WEAVELLM_TRAILER_MAGIC_LEN ${TRAILER_MAGIC_LEN}`,
    `#define WEAVELLM_TRAILER_VERSION ${TRAILER_FORMAT_VERSION}`,
    `#define WEAVELLM_TRAILER_VERSION_LEN ${TRAILER_VERSION_LEN}`,
    `#define WEAVELLM_TRAILER_SIZE_LEN ${TRAILER_SIZE_LEN}`,
    `#define WEAVELLM_TRAILER_HASH_LEN ${TRAILER_HASH_LEN}`,
    "",
    `#define WEAVELLM_TRAILER_LEN ${TRAILER_LEN}`,
    "",
    "#endif /* WEAVELLM_SELFEXTRACT_TRAILER_H */",
    "",
  ].join("\n");
}

/**
 * Base extraction cache dir, mirroring the C stub: $XDG_CACHE_HOME when set
 * and non-empty, else ~/.cache.
 */
export function resolveCacheBase(
  xdgCacheHome: string | undefined,
  home: string | undefined,
): string {
  if (xdgCacheHome !== undefined && xdgCacheHome.length > 0) return xdgCacheHome;
  if (home === undefined || home.length === 0) {
    throw new Error("cannot resolve the extraction cache: neither XDG_CACHE_HOME nor HOME is set");
  }
  return join(home, ".cache");
}

/** Per-payload extraction dir: <base>/weavellm/<payload sha256>. */
export function extractCacheDir(base: string, hash: string): string {
  return join(base, "weavellm", hash);
}

/** WebKitGTK render env used by both the build (for hutch) and the stub. */
export const RENDER_ENV_NAME = "WEBKIT_DISABLE_DMABUF_RENDERER";

/**
 * Merge the DMABUF render override into an env object: the explicit value
 * (even an empty one) wins; otherwise set "1". Undefined values are dropped
 * because spawn envs cannot carry them.
 */
export function withRenderEnv(
  env: Record<string, string | undefined>,
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(env)) {
    if (value !== undefined) out[key] = value;
  }
  if (!(RENDER_ENV_NAME in env)) out[RENDER_ENV_NAME] = "1";
  return out;
}